spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: localhost:8848

  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 131415
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: woyiquanershiniangongli
    database: 0
    jedis:
      pool:
        max-wait: 300
        max-idle: 5
        min-idle: 5

dubbo:
  registry:
    address: nacos://localhost:8848
    username: nacos
    password: nacos

  protocol:
    name: http

  protocols:
    http1:
      id: http1
      name: http
      server: tomcat
      contextpath: /
      port: 8918